run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
