services:
  hermes:
    image: ghcr.io/infydex/hermes:latest
    container_name: hermes
    restart: unless-stopped
    ports:
      - "4376:4376"
    volumes:
      - /srv/docker/hermes/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Kolkata
      # Change the login credentials here:
      - HERMES_USERNAME=admin
      - HERMES_PASSWORD=admin
      
      # Optional: Identify the server sending the alerts (e.g. Edith)
      # - HERMES_SERVER_NAME=Edith
      
      # Optional: To enable clickable links in notifications
      # - HERMES_DOMAIN_URL=https://hermes.example.com
      
      # Optional: Discord webhook configuration
      # - HERMES_DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/xxxx/xxxx
      
      # Optional: SMTP Email configuration
      # - HERMES_SMTP_HOST=smtp.gmail.com
      # - HERMES_SMTP_PORT=587
      # - HERMES_SMTP_USER=your-email@gmail.com
      # - HERMES_SMTP_PASS=your-app-password
      # - HERMES_SMTP_FROM=your-email@gmail.com